### ISSUE TITLE
Teacher can reject / remove signature

### ISSUE THREAD

**Issue by rschrenk** [center-for-learning-management/moodle-mod_edusign#10]
Allow a teacher to reject or remove a signature, so that the User has to sign again.

This allows the teacher to solve technical problems (e.g. the signature field was empty or the signature is not good).

**Comment by dasistwas** [comment]
@winnidat Please update on status of this ticket. Thank you.

**Comment by rschrenk** [comment]
@winnidat Please update on status of this ticket. Thank you.
