### ISSUE TITLE
tests/generator.php missing from repository

### ISSUE THREAD

**Issue by GGeorggg** [center-for-learning-management/moodle-mod_edusign#18]
Hallo @rschrenk 

da fehlt leider ein File damit der unit test durchläuft, kannst du das prüfen ?

```Fatal error: require_once(): Failed opening required '/home/runner/work/eduvidual-src/eduvidual-src/mod/edusign/tests/generator.php' (include_path='/home/runner/work/eduvidual-src/eduvidual-src/lib/pear:.:/usr/share/php') in /home/runner/work/eduvidual-src/eduvidual-src/mod/edusign/feedback/comments/tests/comments_test.php on line 28```

https://github.com/center-for-learning-management/moodle-mod_edusign/blob/9124c3ec5e2b2cc2e86ecf6a03748c2ab2b87fe9/feedback/comments/tests/comments_test.php#L28

danke
Georg

**Comment by rschrenk** [comment]
EduSign ist kein von mir entwickeltes Plugin

**Comment by GGeorggg** [comment]
@rschrenk, sorry ich hatte nur den letzten commit gesehen.
@lassnj wer wird denn das in Zukunft betreuen ?

Danke

**Comment by GGeorggg** [comment]
@lassnj hat ein E-mail an wunderbyte geschickt, hoffe dort wird die fehlende Datei gefunden, andernfalls müsste @center-for-learning-management/think-modular  das nachbauen.

Der Code, welcher das File zur Erstellung der Testcases inkludiert, ist bereits drei Jahre alt und von https://github.com/winnidat erstellt worden.

https://github.com/center-for-learning-management/moodle-mod_edusign/blame/master/feedback/comments/tests/comments_test.php#L28

**Comment by GGeorggg** [comment]
Derzeit showstopper für https://github.com/center-for-learning-management/eduvidual-src/issues/587

**Comment by lassnj** [comment]
*Rückmeldung:*

> Thomas hat hier das assign-Modul geklont und dann ausgemistet und die Unterschriftenfunktion eingebaut. *Es wurden da keine automatischen Tests eingebaut* und die generator.php Datei hat es nie gegeben. Eventuell wird so von einem noch nicht ausgemisteten Teil des assign-Plugins verlangt. Da müsste man wahrscheinlich noch etwas mehr aufräumen.

@GGeorggg für das Plugin gibt es noch keinen automatischen Test, also bitte vorerst mal komplett rausnehmnen aus den Integration Tests.

**Comment by GGeorggg** [comment]
Hallo @lassnj 

bitte meine Pull Requests mergen, dann sind die Tests im default branch weg und erzeugen keine Fehler

danke
Georg

**Comment by lassnj** [comment]
done. LG Julia
