### ISSUE TITLE
Delete Signature

### ISSUE THREAD

**Issue by lassnj** [center-for-learning-management/moodle-mod_edusign#22]
If a signature is reset by the teacher, the status signed at is not deleted. Occurs mainly with group assignments.
Internal Issue: https://github.com/center-for-learning-management/eduvidual-src/issues/271

**Comment by stefan-weber-think-modular** [comment]
@lassnj wurde erledigt: 28a215b9c0f537aa7849790ee5165bfef9240bde

Die Löschroutinen sind hier anders gelöst als beim normalen Assign plugin - hier werden tatsächlich die Records aus der DB gelöscht.

Ich hab das jetzt so beibehalten, und lösche im Fall von Group submissions die jeweils relevanten DB records mit.

**Comment by lassnj** [comment]
Der Status ändert sich nach wie vor nicht und auch der Unterschrift-Löschen-Button bleibt bestehen:
![grafik](https://user-images.githubusercontent.com/22933650/228330961-b44598f5-088c-4b2a-bbd9-477c470efe75.png)

Beim Löschen einer Unterschrift sollte alles in den Ausgangsstatus zurückversetzt werden:
![grafik](https://user-images.githubusercontent.com/22933650/228331309-0785fa33-690c-4ba1-8908-acaed9b44d42.png)

**Comment by stefan-weber-think-modular** [comment]
@lassnj sorry, da war der PR noch nicht gemerged. Ich habe das jetzt nachgezogen, und @gschwed wird es deployen.

**Comment by lassnj** [comment]
Nach deployment keine Änderung: 
![grafik](https://user-images.githubusercontent.com/22933650/229184445-dc9f8a86-f2ca-4d29-bd2c-67ced1471d1d.png)

**Comment by gschwed** [comment]
@stefan-weber-think-modular !
Das passt leider noch immer nicht.

**Comment by stefan-weber-think-modular** [comment]
@lassnj sorry, mein Fehler. Jetzt sollte es wirklich passen: 62c347359a8165bb2a536fe3bcae19e1c6bda5a9
