### ISSUE TITLE
Competencies

### ISSUE THREAD

**Issue by lassnj** [center-for-learning-management/moodle-mod_edusign#23]
Competencies should not be part of an eduSign activity configuration:
![grafik](https://user-images.githubusercontent.com/22933650/211839836-93ac3cd2-c26b-4fee-b91a-8436a73f7ef5.png)

Internal Issue: https://github.com/center-for-learning-management/eduvidual-src/issues/270

**Comment by gschwed** [comment]
@lassnj 
Wer hat das programmiert: Robert? David Bogner? GTN?

**Comment by lassnj** [comment]
Wunderbyte, also David Bogner, die Wartung liegt aber bei uns.

**Comment by gschwed** [comment]
@lassnj 
ok, dann gebe ich das unseren Programmierern

**Comment by stefan-weber-think-modular** [comment]
@lassnj wurde gefixed: 634810cdcee77908c78ea1f44d0a64eaa3d6a8b2
