### ISSUE TITLE
Moodle 4.2 / MDL

### ISSUE THREAD

**Issue by stefan-weber-think-modular** [center-for-learning-management/moodle-mod_edusign#26]
https://github.com/center-for-learning-management/eduvidual-src/issues/1210

mod_edusign ist ein alter fork von mod_assign, deshalb muss hier ebenfalls für [MDL-67526](https://tracker.moodle.org/browse/MDL-67526) deprecated code entfernt werden.

**Comment by stefan-weber-think-modular** [comment]
fixed via 3974c97fb7033cee84d46fffc7e9c536cf8b58d5

**Comment by GGeorggg** [comment]
Hallo @lassnj 

nachdem das Plugin ohnehin nicht auf moodle-hq deployed wird, kann auf ein release verzichtet werden

lg
Georg
