### ISSUE TITLE
edusign should not show up in grading

### ISSUE THREAD

**Issue by lassnj** [center-for-learning-management/moodle-mod_edusign#8]
edusign activities should not show up in the grading overview:
![grafik](https://user-images.githubusercontent.com/22933650/78837145-bd68d780-79f3-11ea-8aca-3b95d48ba8a8.png)

**Comment by rschrenk** [comment]
Tested after the plugin release for Moodle 3.9.
This is still not solved.

**Comment by dasistwas** [comment]
@winnidat  Wie ist der Stand hier?

**Comment by rschrenk** [comment]
@winnidat wie ist der Stand hier?
